name: run-canary-tests
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  canary_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry>=2.0,<3.0"
          poetry env info  # display poetry's env info for debugging
          poetry install  --with test,coverage,lint
    - name: Run Tests
      run: |
        poetry run python tom_registration/tests/run_tests.py --canary